//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HieuSachEntities : DbContext
    {
        public HieuSachEntities()
            : base("name=HieuSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> author { get; set; }
        public virtual DbSet<banner> banner { get; set; }
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<cart_item> cart_item { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<detail_receipt> detail_receipt { get; set; }
        public virtual DbSet<favourite> favourite { get; set; }
        public virtual DbSet<favourite_item> favourite_item { get; set; }
        public virtual DbSet<image_products> image_products { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<publicsher> publicsher { get; set; }
        public virtual DbSet<receipt> receipt { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_roles> users_roles { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
    }
}
